
name: Sign HEX File

on:
  workflow_dispatch:
    inputs:
      oem:
        description: 'OEM Name (e.g., oem1, oem2)'
        required: true
      hex_file:
        description: 'Path to HEX file (optional if auto-triggered)'
        required: false

jobs:
  sign:
    runs-on: windows-latest

    steps:
      - name: Checkout Project_Repo
        uses: actions/checkout@v4

      - name: Checkout private signer-repo
        uses: actions/checkout@v4
        with:
          repository: priyapriya2/signer-repo
          path: signer-repo
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          
      - name: Determine HEX file path
        id: findhex
        run: |
            echo "HEX_FILE=${{ github.event.inputs.hex_file }}" >> $env:GITHUB_ENV
      - name: Find EXE in OEM folder
        id: find_exe
        run: |
             $oem = "${{ github.event.inputs.oem }}"
             $exePath = Get-ChildItem -Path "signer-repo/$OEM Name" -Filter *.exe -Recurse | Select-Object -First 1
             if (-not $exePath) {
                Write-Error "No exe file found in signer-repo/$OEM Name"
                exit 1
               }
             echo "exe_path=$($exePath.FullName)" >> $env:GITHUB_OUTPUT
      
              

      - name: Sign HEX file
        run: |
        
          $keyFile = "signer-repo\\keys\\private.key"
          $signatureFile = "signature.sig"

          & ${{ steps.find_exe.outputs.exe_path }} $env:HEX_FILE $keyFile $signatureFile
          

      - name: Upload signature artifact
        uses: actions/upload-artifact@v4
        with:
          name: hex_signature
          path: signature.sig
